# Generated by Django 5.2 on 2025-04-26 18:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_aboutinfo_name_aboutinfo_profession_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aboutinfo',
            name='profession',
        ),
    ]
