# Generated by Django 5.2 on 2025-04-27 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_remove_aboutinfo_profession'),
    ]

    operations = [
        migrations.CreateModel(
            name='SkilsInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('names', models.CharField(max_length=255, verbose_name='names')),
                ('precent', models.IntegerField(verbose_name='precent')),
            ],
        ),
    ]
