# Generated by Django 5.2 on 2025-04-27 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_skilsinfo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='skilsinfo',
            name='precent',
        ),
        migrations.AddField(
            model_name='skilsinfo',
            name='percent',
            field=models.IntegerField(null=True, verbose_name='percent'),
        ),
        migrations.AlterField(
            model_name='skilsinfo',
            name='names',
            field=models.CharField(max_length=255, null=True, verbose_name='names'),
        ),
    ]
