# Generated by Django 5.2 on 2025-04-27 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_remove_skilsinfo_precent_skilsinfo_percent_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='EducationInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_year', models.IntegerField(verbose_name='start_year')),
                ('end_year', models.IntegerField(verbose_name='end_year')),
                ('degree_univer', models.TextField(verbose_name='univer')),
                ('faculty', models.TextField(verbose_name='faculty')),
                ('description', models.TextField(verbose_name='description')),
            ],
        ),
    ]
