# Generated by Django 5.2 on 2025-04-27 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_educationinfo'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExperienceInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_year', models.IntegerField(verbose_name='start_year')),
                ('end_year', models.IntegerField(verbose_name='end_year')),
                ('experience', models.TextField(verbose_name='experience ')),
                ('univer', models.TextField(verbose_name='univer')),
                ('description', models.TextField(verbose_name='description')),
            ],
        ),
    ]
