# Generated by Django 5.2 on 2025-04-27 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_experienceinfo'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, verbose_name='Your name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Your Email')),
                ('message', models.TextField(verbose_name='Message')),
            ],
        ),
    ]
