# Generated by Django 5.2 on 2025-04-27 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_alter_contactmodel_email_alter_contactmodel_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='FooterInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('facebook', models.URLField(verbose_name='facebook')),
                ('github', models.URLField(verbose_name='GitHub')),
                ('instagram', models.URLField(verbose_name='instagram')),
                ('linkedin', models.URLField(verbose_name='linkedin')),
            ],
        ),
    ]
